### ISSUE TITLE
SSR Compatibility

### ISSUE THREAD

**Issue by artemzakharov** [jonasmedeiros/ng-sticky#5]
I'm currently trying to use this module in an app that leverages server side rendering, but I get this error when attempting to import NgStickyModule:

```
NodeInvocationException: Prerendering failed because of error: C:\Users\...\node_modules\ng-sticky\index.js:1
(function (exports, require, module, __filename, __dirname) { import { Directive, ElementRef, HostListener, Input, NgModule, Renderer2 } from '@angular/core';
^^^^^^

SyntaxError: Unexpected token import
at new Script (vm.js:51:7)
at createScript (vm.js:138:10)
at Object.runInThisContext (vm.js:199:10)
at Module._compile (module.js:624:28)
at Object.Module._extensions..js (module.js:671:10)
at Module.load (module.js:573:32)
at tryModuleLoad (module.js:513:12)
at Function.Module._load (module.js:505:3)
at Module.require (module.js:604:17)
at require (internal/module.js:11:18)
```

**Comment by jonasmedeiros** [comment]
@artemzakharov do you have a plunker with that or demo.

**Comment by artemzakharov** [comment]
I actually ended up just putting the directive directly into my project instead of importing them via NPM, and that solved the issue for me. I'll put together a demo if this issue comes up again but this ad-hoc solution is good enough at the moment.
